version: "3.9"

services:
  main:
    ports:
      - 5000:5000
    volumes:
      - main:/app
      - /app/.git
      - /app/infrastructure

volumes:
  main:
    driver_opts:
      type: none
      device: $PWD
      o: bind
