version: "3.9"

services:
  main:
    ports:
      - 5000:5000
    volumes:
      - main:/usr/src/app
      - /usr/src/app/.git
      - /usr/src/app/infrastructure

volumes:
  main:
    driver_opts:
      type: none
      device: $PWD
      o: bind
